kind: pipeline
type: docker
name: Publish Docker Images

trigger:
  event:
    exclude: pull_request

steps:
  # - name: apache-image
  #   image: plugins/docker
  #   settings:
  #     username:
  #       from_secret: docker-user
  #     password:
  #       from_secret: docker-key
  #     repo: randomman552/nextcloud-ffmpeg
  #     tags:
  #       - latest
  #       - apache
  #       - stable
  #       - stable-apache

  # - name: fpm-alpine-image
  #   image: plugins/docker
  #   settings:
  #     username:
  #       from_secret: docker-user
  #     password:
  #       from_secret: docker-key
  #     repo: randomman552/nextcloud-ffmpeg
  #     dockerfile: Dockerfile.fpm-alpine
  #     tags:
  #       - fpm-alpine
  #       - stable-fpm-alpine

  # - name: fpm-image
  #   image: plugins/docker
  #   settings:
  #     username:
  #       from_secret: docker-user
  #     password:
  #       from_secret: docker-key
  #     repo: randomman552/nextcloud-ffmpeg
  #     dockerfile: Dockerfile.fpm
  #     tags:
  #       - fpm
  #       - stable-fpm

  - name: finished-webhook
    image: plugins/webhook
    # depends_on:
    #   - apache-image
    #   - fpm-image
    #   - fpm-alpine-image
    settings:
      urls:
        from_secret: notification-webhook
      template: |
        {
          "title": "${DRONE_BUILD_STATUS^} for ${DRONE_REPO}",
          "message": "Build `${DRONE_BUILD_NUMBER}` triggered by `${DRONE_BUILD_EVENT}` on `${DRONE_BRANCH}` branch\n\nCommit: [`${DRONE_COMMIT_MESSAGE}`](${DRONE_COMMIT_LINK}) by ${DRONE_COMMIT_AUTHOR}\n\n[View build](${DRONE_BUILD_LINK})\n\n[View source](${DRONE_REPO_LINK})",
          "priority": 5,
          "extras": {
            "client::display": {
              "contentType": "text/markdown"
            },
            "client::notification": {
              "click": { "url": "${DRONE_BUILD_LINK}" }
            }
          }
        }
