kind: pipeline
type: docker
name: Build and Push Apache Image

trigger:
    event:
        - push

steps:
    - name: Push Stable Apache
      image: plugins/docker
      depends_on: []
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          tags:
              - latest
              - apache
              - stable
              - stable-apache
---
kind: pipeline
type: docker
name: Build and Push FPM Image

trigger:
    event:
        - push

steps:
    - name: Push Stable Apache
      image: plugins/docker
      depends_on: []
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          tags:
              - fpm
              - stable-fpm

---
kind: pipeline
type: docker
name: Build and Push FPM Alpine Image

trigger:
    event:
        - push

steps:
    - name: Push Stable Apache
      image: plugins/docker
      depends_on: []
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          tags:
              - fpm-alpine
              - stable-fpm-alpine
