kind: pipeline
type: docker
name: Publish Docker Images

trigger:
    branch:
        - master
        - main
    event:
        exclude:
            - pull_request
    action:
        exclude:
            - opened

steps:
    # Apache image
    - name: apache-image
      image: plugins/docker
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          tags:
              - latest
              - apache
              - stable
              - stable-apache

    # FPM Alpine image
    - name: fpm-alpine-image
      image: plugins/docker
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          dockerfile: Dockerfile.fpm-alpine
          tags:
              - fpm-alpine
              - stable-fpm-alpine

    # FPM Image
    - name: fpm-image
      image: plugins/docker
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          dockerfile: Dockerfile.fpm
          tags:
              - fpm
              - stable-fpm

    # Reporting
    - name: build-reporter
      image: randomman552/drone-build-reporter
      depends_on:
          - apache-image
          - fpm-alpine-image
          - fpm-image
      settings:
          gotify_token:
              from_secret: gotify-token
          gotify_url:
              from_secret: gotify-url
          discord_webhook:
              from_secret: discord-webhook
      when:
          status:
              - failure
              - success
