kind: pipeline
type: docker
name: Apache Image

trigger:
    event:
        - push

steps:
    - name: Build and Push Image
      image: plugins/docker
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          tags:
              - latest
              - apache
              - stable
              - stable-apache
---
kind: pipeline
type: docker
name: FPM Image

trigger:
    event:
        - push

steps:
    - name: Build and Push Image
      image: plugins/docker
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          dockerfile: Dockerfile.fpm
          tags:
              - fpm
              - stable-fpm

---
kind: pipeline
type: docker
name: FPM Alpine Image

trigger:
    event:
        - push

steps:
    - name: Build and Push Image
      image: plugins/docker
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          dockerfile: Dockerfile.fpm-alpine
          tags:
              - fpm-alpine
              - stable-fpm-alpine
