kind: pipeline
type: docker
name: Push Images

trigger:
    event:
        - push

steps:
    - name: Push Stable Apache
      image: plugins/docker
      depends_on:
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          tags:
              - latest
              - apache
              - stable
              - stable-apache

    - name: Push FPM
      image: plugins/docker
      depends_on:
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          dockerfile: Dockerfile.fpm
          tags:
              - fpm
              - stable-fpm

    - name: Push FPM Alpine
      image: plugins/docker
      depends_on:
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/nextcloud-ffmpeg
          dockerfile: Dockerfile.fpm-alpine
          tags:
              - fpm-alpine
              - stable-fpm-alpine
