name: List upstream tags

on:
  workflow_dispatch:
    inputs:
      variant:
        required: true
        default: apache
        type: choice
        options:
          - apache
          - fpm
          - fpm-alpine
env:
  VARIANT: apache
  PREFIXES: '["stable", "31", "32", "33"]'
  REGISTRY: 'ghcr.io'
  REPOSITORY: ${{ github.repository }}

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch apache tags from upstream image
        run: |
          python .github/scripts/fetch_tags.py
