name: List upstream tags

on:
  workflow_dispatch:
env:
  PREFIXES: '["stable", "31", "32", "33"]'

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch apache tags from upstream image
        run: |
          python .github/scripts/fetch_tags.py "apache" "$PREFIXES"

      - name: Fetch fpm tags from upstream image
        run: |
          python .github/scripts/fetch_tags.py "fpm" "$PREFIXES"

      - name: Fetch fpm-alpine tags from upstream image
        run: |
          python .github/scripts/fetch_tags.py "fpm-alpine" "$PREFIXES"
